name: my_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.6

  # Story maker dependencies
  image_picker: ^1.0.7
  video_player: ^2.8.2
  giphy_picker: ^3.0.1
  just_audio: ^0.9.36
  path_provider: ^2.1.2
  google_fonts: ^6.1.0

  # Note: photo_filters package doesn't exist in pub.dev
  # We'll implement filters manually using ColorFilter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
